### ISSUE TITLE
Plugin logic how to handle query params?

### ISSUE THREAD

**Issue by Dunken** [BigstickCarpet/swagger-express-middleware#32]
First of all thank you for providing this great framework!

It looks like swagger-express-middleware just applies query string parameters as filter for existing fields. However I would like to apply my own logic (e.g. `priority=high` should return all items of a collection where some condition is fulfilled). Can I do this?

**Comment by BigstickCarpet** [comment]
Yes, you can do that using [custom middleware](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/samples/walkthrough2.md#custom-middleware).  You can completely replace the default functionality with your own, or you can inject your own logic before running the default functionality.

**Comment by Dunken** [comment]
OK, got it, thanks!
