### ISSUE TITLE
Request body validated not according to Swagger 2.0 spec.

### ISSUE THREAD

**Issue by IvanGoncharov** [BigstickCarpet/swagger-express-middleware#6]
According to [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object) swagger inside **schema object** support only **limited subset** of JSON Schema draft4 and extend it with **custom keywords**.

So, you don't use "discriminator" and "readOnly" keywords during validation that mean you don't fully support Swagger 2.0 spec.

Personally, I think it's a problem in Swagger spec.
So I created swagger-api/swagger-spec#333 feature request to make Swagger compatible with JSON Schema.
And I want library authors took part in that discussion.

**Comment by BigstickCarpet** [comment]
This is actually a bug in [Swagger Parser](https://github.com/BigstickCarpet/swagger-parser), which Swagger Express Middleware uses to parse the swagger docs.   Thanks for pointing it out.  I'll look into it and get it fixed.

**Comment by IvanGoncharov** [comment]
It's totally unrelated to Swagger Parse, probably I confused you with issue description.
Following call sequence will illustrate problem:
[param-parser.js:96](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/lib/param-parser.js#L96) req.body = parseParameter(param, req.body, **param.schema**);
[param-parser.js:147](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/lib/param-parser.js#L147) return new JsonSchema(**schema**).parse(value);
[json-schema.js:46](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/lib/helpers/json-schema.js#L46) return parseObject(**this.schema**, value, propPath);
[json-schema.js:530](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/lib/helpers/json-schema.js#L530) jsonValidate(**schema**, parsedValue, propPath || '');
[json-schema.js:211](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/lib/helpers/json-schema.js#L211) if (tv4.validate(value, **schema**)) {

So as you can see, tv4 used to validate body parameter according to Swagger [schema object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object).
But JSON Schema and Swagger schema object incompatible, and that is issue in nutshell.

**Comment by IvanGoncharov** [comment]
Initially I created this issue to bring attention to https://github.com/OAI/OpenAPI-Specification/issues/333
So it can't be fixed without writing custom JSON schema validator which doesn't happen any time soon.
