### ISSUE TITLE
Router middleware to dispatch based on operationId

### ISSUE THREAD

**Issue by bachp** [BigstickCarpet/swagger-express-middleware#9]
It would be nice to have a router middleware that would simplify the creation of handlers for methods based on the [operationId](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-5).

The idea would be as follows.

Based on the following snippet

```
/pets:
    get:
      summary: List all pets
      operationId: listPets
```

one would create an object and use something like the following snippet to create the router.

```
var petrouter = {
    listPets: function(req, res, next) {
        // Do something
    }
};
app.use(middleware.router(petrouter));
```

Instead of having to the the following for ever method defined in the specification file

```
app.patch('/pets', function(req, res, next) { 
    // Do something
});
```

The advantage I see would be that the redundancy between what method to use (`GET`, `PUT`, ...) and the exact path specification could be avoided. The only thing that maps between the swagger spec and the implementation is the operationId.

What do you think? Would this be a sensible enhancement?

**Comment by BigstickCarpet** [comment]
Good news.  This is already on the roadmap.  It won't actually be done as part of Swagger Express Middleware though.  It's part of [Swagger Server](https://github.com/BigstickCarpet/swagger-server), which sits on top of Swagger Express Middleware.

**Comment by bachp** [comment]
Good to hear. I already saw swagger server, however it was not clear to me what's the relation so Swagger Express Middleware and what is adds on top of it.
Maybe you could explain the reason why there are two projects and what they add on top of each other in an FAQ.

**Comment by BigstickCarpet** [comment]
Swagger Server is still in development, so it doesn't currently add a lot on top of Swagger Express Middleware, but the differences will be much more obvious once it's finished.   

Basically, Swagger Express Middleware is just middleware that you can use to build your own Express app.  It's still up to you to define your routes, add handlers, etc.   

Swagger Server will be an already-built Express app that requires little to no setup or understanding of Express.  It will automatically setup your routes and handlers by looking for files/folders that match the names of your API's paths and operationIDs.

**Comment by bachp** [comment]
Thanks for clarifying. Based on your explanation I think it might still be nice to have the operationId routing in a special middleware that can then be used by swagger-server.

**Comment by BigstickCarpet** [comment]
Good point.  We'll probably end up releasing _all_ of Swagger Server's middleware as separate NPM modules, so they can be used standalone as well.

**Comment by bachp** [comment]
Ok sounds good. I will close the issue then.

**Comment by nemaniarjun** [comment]
Is this a part of `swagger-express-middleware` or not?

**Comment by JonnyWaffles** [comment]
I too would like to know if this is a part of the `swagger-express-middleware`. The documentation is unclear as to how you bind operationId names to functions. The sample projects don't see to even have js functions mapping the operationId in the YAML, so I'm not entirely sure how to wire any any of this up.
