### ISSUE TITLE
How to deal with unwanted extra properties on objects?

### ISSUE THREAD

**Issue by Calrain** [BigstickCarpet/swagger-express-middleware#94]
I'm new to this library and can't work out how to block extra properties consumers of a REST API may send through.

With validation turned on, there doesn't seem to be a way to read `req.swagger.params.body` if you wanted to read the validated contents of a requests `body`.

Also there doesn't seem to be a way in yaml to only allow parameters specified.

If a parameter is missing, and yaml has it marked as `required` then appropriate error messages are provided.

Is there a way to deal with extra unwanted properties coming through?

**Comment by BigstickCarpet** [comment]
Swagger API specs are written in [JSON Schema](http://json-schema.org/).  By default, JSON Schema allows extra properties that aren't defined in the schema.  You can disable this via the `additionalProperties` keyword.  See [this tutorial](https://spacetelescope.github.io/understanding-json-schema/reference/object.html) for examples.

**Comment by Calrain** [comment]
Thanks, this solved the problem 👍
