### ISSUE TITLE
Looking for example of multiple .yml files to hold schema

### ISSUE THREAD

**Issue by Calrain** [BigstickCarpet/swagger-express-middleware#95]
I'm looking for an example of how to use multiple .yml files to document a schema.

The example line I have looked at is:
`middleware('PetStore.yaml', app, function(err, middleware) {`
but I'm not sure how you provide a directory or object full of file references in place of the `'PetStore.yaml'` single file name reference.

swagger-express-middleware mentions it uses the swagger-parser library, and swagger-parser supports the  [bundle() function](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/swagger-parser.md#bundleapi-options-callback) which seems to be able to take a directory and create a single object from which you can generate swagger documentation.

Is there any working example of either using the 'bundle' feature of swagger-parser, or another method of bundling together .yml files?

Currently my .yml file is over 2,000 lines long and it would be great to simplify it.

**Comment by BigstickCarpet** [comment]
You can split your API definition into multiple files using [Reference Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#reference-object) (a.k.a. the `$ref` keyword).  

[Here's a live example](http://bigstickcarpet.com/swagger-parser/www/index.html), which is a single API definition that's split-up into [`swagger.yaml`](http://bigstickcarpet.com/swagger-parser/www/swagger.yaml), [`pet.yaml`](http://bigstickcarpet.com/swagger-parser/www/pet.yaml), [`pet-owner.yaml`](http://bigstickcarpet.com/swagger-parser/www/pet-owner.yaml), and [`error.json`](http://bigstickcarpet.com/swagger-parser/www/error.json).

**Comment by Calrain** [comment]
Ah perfect, I am using `$ref` but only to definitions in the same file. This will make life much easier. 
Thanks very much.

**Comment by BigstickCarpet** [comment]
Cool, glad to help
